### ISSUE TITLE
Fatal error of surface interface

### ISSUE THREAD

**Issue by yyachi** [misasa/medusa#132]
```
F, [2019-07-24T15:14:40.072731 #15723] FATAL -- : 
ActionView::Template::Error (undefined method `<' for nil:NilClass):
    1: <% if @surface.globe? %>
    2:   <%= ActsAsMappable::Mappable::HtmlGenerator.generate(lat: 0, lng: 0, zoom: 0, width: 300, height: 300) %>
    3: <% else %>
    4:   <%= @surface.map(class: "large-map", add_spot: true) %>
    5: 
    6:   <%= form_for Spot.new, url: surface_spots_path(@surface) do |f|%>
    7:     <%= hidden_field_tag :tab,"" %>
  app/models/surface.rb:116:in `block in bounds'
  app/models/surface.rb:112:in `bounds'
  app/models/surface.rb:144:in `affine_matrix_for_map'
  app/decorators/surface_decorator.rb:62:in `map'
  app/views/surfaces/family.html.erb:4:in `_app_views_surfaces_family_html_erb___600418936205634381_70057070085540'
  app/controllers/surfaces_controller.rb:45:in `family'

```

**Comment by yyachi** [comment]
solved
