### ISSUE TITLE
rake assets:precompile error on calibrator.js

### ISSUE THREAD

**Issue by yyachi** [misasa/medusa#52]
```
$ bundle exe rails c -e production
Loading production environment (Rails 4.0.2)
irb(main):001:0> JS_PATH = "app/assets/javascripts/**/*.js";
irb(main):002:0* Dir[JS_PATH].each do |file_name|
irb(main):003:1* puts "\n#{file_name}"
irb(main):004:1> puts Uglifier.compile(File.read(file_name))
irb(main):005:1> end

app/assets/javascripts/sortable.js
!function(e){e(document).ready(function(){e(".sortable").sortable(),e(".sortable").disableSelection()})}(jQuery);

app/assets/javascripts/notification.js
!function(n){function a(a,i,o){var c=n("#notification-modal");c.find("div.modal-header").removeClass("alert-success alert-warning alert-danger").addClass(a),n("#notification-modal-label").html(i),c.find("div.modal-body").html(o),c.modal()}n.notification={success:function(n){a("alert-success","<span class='glyphicon glyphicon-ok-circle'></span> Success",n)},warning:function(n){a("alert-warning","<span class='glyphicon glyphicon-exclamation-sign'></span> Warning",n)},error:function(n){a("alert-danger","<span class='glyphicon glyphicon-remove-circle'></span> Error",n)},errorMessages:function(a){var i=n("<dl>");i.addClass("dl-horizontal"),n.each(a,function(n,a){i.append("<dt>"+n+"</dt><dd>"+a+"</dd>")}),n.notification.error(i)},modalObject:function(){return n("#notification-modal")}}}(jQuery);

app/assets/javascripts/calibrator.js
ExecJS::ProgramError: Unexpected token punc «(», expected punc «:» (line: 73, col: 16, pos: 2764)

Error
    at new JS_Parse_Error (<eval>:2357:10748)
    at js_error (<eval>:2357:10967)
    at croak (<eval>:2357:19192)
    at token_error (<eval>:2357:19329)
    at expect_token (<eval>:2357:19552)
    at expect (<eval>:2357:19690)
    at <eval>:2357:28596
    at <eval>:2357:20063
    at expr_atom (<eval>:2357:27352)
    at maybe_unary (<eval>:2357:30102)
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:34:in `rescue in block in eval'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:28:in `block in eval'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `call'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:27:in `eval'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:19:in `exec'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/uglifier-2.4.0/lib/uglifier.rb:184:in `really_compile'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/uglifier-2.4.0/lib/uglifier.rb:108:in `compile'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/uglifier-2.4.0/lib/uglifier.rb:76:in `compile'
        from (irb):4:in `block in irb_binding'
        from (irb):2:in `each'
        from (irb):2
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:90:in `start'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/commands/console.rb:9:in `start'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:62:in `<top (required)>'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/app_rails_loader.rb:43:in `require'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/app_rails_loader.rb:43:in `block in exec_app_rails'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/app_rails_loader.rb:32:in `loop'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/app_rails_loader.rb:32:in `exec_app_rails'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/lib/rails/cli.rb:6:in `<top (required)>'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/bin/rails:9:in `require'
        from /srv/stone/shared/bundle/ruby/2.1.0/gems/railties-4.0.2/bin/rails:9:in `<top (required)>'
        from /srv/stone/shared/bundle/ruby/2.1.0/bin/rails:23:in `load'
        from /srv/stone/shared/bundle/ruby/2.1.0/bin/rails:23:in `<main>'irb(main):006:0>

```

**Comment by yyachi** [comment]
#53
